plugins {
	id 'java'
	id 'org.springframework.boot'
}

dependencies {
	implementation project(':common:event')
	implementation project(':common:event-dispatcher')
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation project(':common:monitoring')
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.springframework.boot:spring-boot-micrometer-metrics-test'
	testImplementation testFixtures(project(':common:monitoring'))
	testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
	testImplementation 'org.testcontainers:testcontainers-kafka'
}
