server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/article?allowPublicKeyRetrieval=true&useSSL=false
  kafka:
    bootstrap-servers: localhost:19092

snowflake:
  node-id: 1
