spring:
  application:
    name: comment
  datasource:
    url: jdbc:mysql://localhost:3306/comment
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

snowflake:
  node-id: 0
